version: "3.7"
services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: mytonestest
    # DATABASE_URL="postgresql://postgres:password@mytones_proj-db-1:5432/mytonestest"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
    - customnetwork
  redis:
    image: redis
    working_dir: /redis
    ports:
      - '6379:6379'
    networks:
    - customnetwork
  web:
    depends_on:
      - db
      - redis
    links:
      - db
      - redis
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '5000:5000'
    networks:
    - customnetwork
networks:
  customnetwork:
